# Generated by Django 4.1.7 on 2023-03-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userfiles_remove_user_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfiles',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
