# Generated by Django 4.1.7 on 2023-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_userfiles_user_id_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='user-cover'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='user-profile'),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='resume',
            field=models.FileField(blank=True, upload_to='user-resume'),
        ),
    ]
