# Generated by Django 4.1.7 on 2023-03-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userfiles_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
