# Generated by Django 4.1.7 on 2023-03-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_user_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='password',
            new_name='location',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='company-cover'),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='company-profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
