# Generated by Django 4.1.7 on 2023-03-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_company_company_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
