# Generated by Django 4.1.7 on 2023-03-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_company_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='email',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='name',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='password',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone',
        ),
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
