# Generated by Django 4.1.7 on 2023-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_email_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruitment_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
