# Generated by Django 4.1.7 on 2023-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_job_recruitment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('notification', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
            ],
        ),
    ]
